# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b4038051418d1bc7d1d58311e6f824c41dc54b265a2b716cad95749613fa69dc55115d51cdac3780b1282618622ffb9d614039ae03a7ca757b870813fae559

test:
  secret_key_base: 617e5ce7c6fc853688fdf952ba80396ed6fb671aa44c8c145ab3d09f0383f753414e33c639c0f9a03459242e744b094b4805aa45e8fd413891a3798e0e83f14a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
